export const ACTIONS = {
  START_GAME: 'START_GAME',
  PLACE_BET: 'PLACE_BET',
  RESOLVE_ROUND: 'RESOLVE_ROUND',
  EXIT_TO_LANDING: 'EXIT_TO_LANDING',
  LOAD_LEADERBOARD: 'LOAD_LEADERBOARD',
  SAVE_SCORE: 'SAVE_SCORE',
  RESET_SESSION: 'RESET_SESSION',
}

